### ISSUE TITLE
Would be better if TreeNode<T>

### ISSUE THREAD

**Issue by lvyandev** [baumths/flutter_tree_view#10]
Very nice lib!
It would be better if treeNode has generic type to make it easier to access data's fields without cast.

**Comment by mbaumgartenbr** [comment]
Hey, thank you for trying the package out!

I have worked with that before but <T> was lost somewhere and I still had to cast it in the example.

Any suggestions on how to approach this without making every class accept generics?

**Comment by lvyandev** [comment]
> Any suggestions on how to approach this without making every class accept generics?

For now I haven't figured out a solution, or It might be suggested to write generics everywhere according to [linter:rules - always_specify_types](https://github.com/dart-lang/linter/blob/master/lib/src/rules/always_specify_types.dart)

**Comment by mbaumgartenbr** [comment]
> For now I haven't figured out a solution, or It might be suggested to write generics everywhere according to [linter:rules - always_specify_types](https://github.com/dart-lang/linter/blob/master/lib/src/rules/always_specify_types.dart)

It's also written in there that we should use `Object` if we need that variable to override `==` and `hashcode`.

With generics I can't guarantee that the variable won't be dynamic.

**Comment by lvyandev** [comment]
Sure, I didn't see that.  Could give it a try
