### ISSUE TITLE
Drag and Drop functionality

### ISSUE THREAD

**Issue by Talgat777** [baumths/flutter_tree_view#17]
Is there a way to implement drag and drop functionality? Maybe just reordering?

**Comment by mbaumgartenbr** [comment]
Hey @Talgat777!

I'm currently working on this feature for version 1.0 but its beeing really tough to find the right API implementation for drag & drop of hierarchical data, dealing with levels and such...

I can't promise anything, neither give a release date.

**Comment by devon** [comment]
@mbaumgartenbr This package may help for drag-drop https://github.com/knopp/flutter_reorderable_list. It's also a list. But we need to deal with the levels.

**Comment by mbaumgartenbr** [comment]
Hey @devon!

Thank you for the suggestion, I appreciate it!

I have already looked through all packages on pub to decide upon the APIs, none of them are quite easy to add nesting level handling.

However, I have already found an API that works fine. Although it's very opinionated and not as customizable as I would want it to be, but it works.  I just haven't had time to work on the package lately.

You can track the progress of the new APIs on the `wip-1.0` branch. I just didn't start writing the drag and drop logic there yet, although it is complete and ready in a private repo (missing docs and polishing, not very customizable atm.).

I'll resume working at v1.0 as soon as this other thing is done. (can't promise anything, but I'd expect to be done in about a week or so).

**Comment by devon** [comment]
@mbaumgartenbr That's great news. I will help to test the feature 😁.

**Comment by tes735** [comment]
I'm currently working on this as well. I got the drag/drop to work. I have "lines" which are just nodes with no children between my nodes that only show when you've dragged a node over it to give the user an idea of where to drop, and where the node's new location will be in the tree. I came here looking for the best way to reorder the list after dropping. It looks like I can track the location outside the library, take the drop targets location as a point for where the new node should be, and recreate the entire tree's data/repaint. This should work, but I'm not sure about the performance. Ideas?

**Comment by baumths** [comment]
> I'm currently working on this as well. I got the drag/drop to work. I have "lines" which are just nodes with no children between my nodes that only show when you've dragged a node over it to give the user an idea of where to drop, and where the node's new location will be in the tree. I came here looking for the best way to reorder the list after dropping. It looks like I can track the location outside the library, take the drop targets location as a point for where the new node should be, and recreate the entire tree's data/repaint. This should work, but I'm not sure about the performance. Ideas?

I have a semi finished Drag and Drop implementation based on Draggable + DragTarget that should've got released along with version `1.0` but I made some modifications to the tree API that changed how that DnD implementation works and I haven't had time to work on it since then, but it is my top priority and I'm planning to catch up on it in the following days/weeks (depending on how difficult it would be to adapt and how well I can manage my spare time).

**Comment by tes735** [comment]
Gotcha. Yeah, it's a bear to get going. I hadn't even gotten to making it droppable on top of another item so that it could become a child of that "folder." There's a lot to it.

**Comment by JerContact** [comment]
Just curious where this is at!  Would love to have this functionality, but totally realize it's a lot....thanks for the great lib!

**Comment by Talgat777** [comment]
@baumths version 1.x works great! Well done! Looking forward checking drag & drop! Any ETA?

**Comment by baumths** [comment]
Yeah, about that... 😅

My life is currently upside-down. The "almost no spare time" became "no spare time at all" quite quickly. I haven't touched my computer in a month or so.

Unfortunately there are no updates on this, the state is the same: I have a *new* working implementation that needs polishing and docs. I may find time to just push that branch to gh to let people use it with a git ref on pubspec in its current state, but I'm not sure about that. (It might be cool to get some feedback, though)

**Comment by Talgat777** [comment]
Please do! Someone might finish it and create PR for you to review.

Hopefully, "no spare time at all" in a good way :) Good luck and thanks for the library!

**Comment by JerContact** [comment]
I'm getting this when putting that in the dependencies:

```
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
exit code 69
```

**Comment by baumths** [comment]
> I'm getting this when putting that in the dependencies:
> 
> ```
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> exit code: 128
> exit code 69
> ```

My bad, you probably have to use the http url instead of the  ssh one:

https://github.com/baumths/flutter_tree_view.git

**Comment by JerContact** [comment]
that worked!
