### ISSUE TITLE
some error occurred when its wrapped in a singlechildscrollview that scrolls horizontally.

### ISSUE THREAD

**Issue by pickupsb** [baumths/flutter_tree_view#33]
its a listview.custom inside this widget , when i replace it with column no error occurred but its difficult to scroll to a specific treenode ,to fix that is gonna need more efforts.
any solution?

**Comment by mbaumgartenbr** [comment]
Hey @pickupsb, thank you for using the package!

I don't think I quite understand the issue here. Could you provide a code sample or a simple reproducible example?
