### ISSUE TITLE
An error is reported when the outer layer is wrapped with a horizontal rolling component

### ISSUE THREAD

**Issue by XZ07s** [baumths/flutter_tree_view#36]
Failed assertion: line 1979 pos 12: 'hasSize'

`PostControllerScope(
        controller: appController,
        child: FutureBuilder<void>(
          future: appController.hello(),
          builder: (_, __) {
            if (appController.isInitialized) {
              return ValueListenableBuilder<TreeViewTheme>(
                valueListenable: appController.treeViewTheme,
                builder: (_, treeViewTheme, __) {
                  return Scrollbar(
                    isAlwaysShown: true,
                    controller: appController.scrollController,
                    child: SingleChildScrollView(
                      child: TreeView(
                        controller: appController.treeController,
                        theme: treeViewTheme,
                        scrollController: appController.scrollController,
                        nodeHeight: appController.nodeHeight,
                        nodeBuilder: (_, __) => GestureDetector(
                          child: ValueListenableBuilder<ExpansionButtonType>(
                            valueListenable: appController.expansionButtonType,
                            builder: (context, ExpansionButtonType buttonType, __) {
                              return Row(
                                  children: const [
                                    LinesWidget(),
                                    NodeWidgetLeadingIcon(useFoldersOnly: true),
                                    IconChip(),
                                    SizedBox(width: 8),
                                    Expanded(child: NodeTitle()),
                                  ]
                              );
                            },
                          ),
                        ),
                      ),
                    ),
                  );
                },
              );
            }
            return const Center(child: CircularProgressIndicator());
          },
        ),
      )`

**Comment by opimand** [comment]
Need horizontal scrolling for tree, same problem

**Comment by baumths** [comment]
Waiting on https://flutter.dev/go/2D-Foundation
