### ISSUE TITLE
Best Way to Scroll Horizontally and Vertically

### ISSUE THREAD

**Issue by aekaero** [baumths/flutter_tree_view#47]
I am trying to use InteractiveViewer to try to scroll a large tree.  The horizontal scrolling works normal, however my vertical scrolling snaps back to my original view as soon as I stop the scroll.   I am new to flutter_tree_view as well as InteractiveViewer, and moderately familiar with flutter.  Is this a bug, or am I setting something wrong?   This snippet uses your MinimalTreeView unaltered.  Thank you!

InteractiveViewer(
                        constrained: false,
                        child: Container(
                          height: 1000,
                          width: 1000,
                          child: 
                              MinimalTreeView(),
                        )),

**Comment by baumths** [comment]
Hey @aekaero. Thank you for using the package!

Is that `InteractiveViewer` required for what you're building or is it an attempt to make the tree view scroll horizontally?

If all you want is for the tree view to also scroll horizontally and you're willing to use a predefined width constraint (`1000` as in your code snippet), you could probably get away with the following setup:

> I'm writing from my phone, sorry for any mistakes

```dart
@override
Widget build(BuildContext context) {
  return SingleChildScrollView(
    scrollDirection: Axis.horizontal,
    child: SizedBox(
      width: 1000,
      child: MinimalTreeView(),
    ),
  );
}
```

I have not tested the code above (as I'm on my phone) but I'm pretty sure I've done it like that in the past.

> Btw, the flutter team is working on two dimensional scroll views, once that reaches stable I'll try to use that implementation to add out-of-the-box support for horizontal scrolling to this package. You can checkout the proposal at https://flutter.dev/go/2D-Foundation.

Try the above and let me know if it works.
