### ISSUE TITLE
Adding a vertical scroll bar to the tree 

### ISSUE THREAD

**Issue by aekaero** [baumths/flutter_tree_view#48]
@baumths, Thanks for the earlier help with horizontal and vertical scroll.  I apologize that I do not know git well enough yet to message you direct with this question (I assume it is possible).   Could you please advise how I could add a vertical scroll bar to a tree?  It looks like there are several inherited properties used in your package that might do this... but I am sorry I do not know how to set them.  1M thanks.

**Comment by baumths** [comment]
Hey @aekaero!

> I'm assuming we are following on our previous conversation on #47.

Flutter implicitly adds the `Scrollbar` widget around your scroll views depending on the target platform.

If I remember right, in the past I ran into an issue where flutter would not link the scrollbars correctly on nested scroll views and I'm not sure if that issue have been fixed.

The fix back then was to create two `ScrollController`s, one for each direction and provide them to the respective scroll view + scrollbar combo.

Have a look at the [Scrollbar docs](https://api.flutter.dev/flutter/material/Scrollbar-class.html). Maybe even the [thumbVisibility](https://api.flutter.dev/flutter/material/Scrollbar/thumbVisibility.html) property which I'm pretty sure is what you are looking for.

Let me know if it helped!

**Comment by aekaero** [comment]
Thanks  for the suggestions.   No Joy yet, but still working on  it.  I will hope to update latter today

**Comment by aekaero** [comment]
Under the saying "Better Late Then Never" I wanted to paste two solutions to offering Horizontal and Vertical Scroll bars as it appears that others ask this from time to time.
Thanks again for the help and the great tree package!

Using native scroll bars: however this method has the problem of the vertical scroll bar leaving the screen as the horizontal viewport is scrolled to the right.  This version also adjusts for PC platforms that implicitly add scroll bars  This is what you alluded to in your comments above:

import 'package:flutter/material.dart';
import 'package:learn201/common/ui/minimal_tree.dart';

class ScrollTreeView extends StatelessWidget {
  const ScrollTreeView({super.key});

// This Class uses the native scroll bar componets of flutter
// to provide a horizontal and vertical scroll bar for Fancy_Tree
// One limitating of this approach is that scrolling horizonally
// will cause the vertical scroll bar to leave the screen.
// This is because the vertical
// scroll bar is nested inside a SingleChildScroll view that
// creates the horizontal scroll bar.

  @override
  Widget build(BuildContext context) {
    // Define a horizontal Scroll Controller.
    // Use PrimaryScrollController for the Vertical
    final horizScrollController = ScrollController();

    // Dummy platformset here for testing...
    const currentPlatform = TargetPlatform.iOS;

    // Only manually add a `Scrollbar` when not on desktop platforms.
    switch (currentPlatform) {
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        return paintTree(
          false,
          horizScrollController,
        );
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
      case TargetPlatform.iOS:
        return
            // SafeArea is critical for proper placement of the
            // ScrollBars - otherwise they paint incorrectly
            // over the tree
            SafeArea(
          child: Scrollbar(
            thickness: 7,
            radius: const Radius.circular(4),
            thumbVisibility: true,
            trackVisibility: true,
            controller: horizScrollController,
            scrollbarOrientation: ScrollbarOrientation.bottom,
            child: paintTree(
              true,
              horizScrollController,
            ),
          ),
        );
    }
  }

  Widget paintTree(
    bool isScroll,
    ScrollController horizScrollController,
  ) {
    // Nest the two scroll bars if isScroll==true, otherwise let
    // the implicit scroll bars form on other platforms.
    //
    // Create common code and store in a common Widget
    // A bit of padding at the bottom evens out the look of the
    // vert vs horiz scroll bars
    const Widget vertChild = Padding(
      padding: EdgeInsets.only(bottom: 15),
      child: MinimalTreeView(),
    );

    return SingleChildScrollView(
      controller: horizScrollController,
      scrollDirection: Axis.horizontal,
      child: SizedBox(
        height: 300,
        width: 1000,
        child: isScroll
            ? const Scrollbar(
                thickness: 7,
                radius: Radius.circular(4),
                thumbVisibility: true,
                trackVisibility: true,
                scrollbarOrientation: ScrollbarOrientation.left,
                // Can use PrimarlyScrolController if using MinimalTree()
                child: vertChild,
              )
            : vertChild,
      ),
    );
  }
}

Using Cross_Scroll to create two scroll bars that remain in place as tree is scrolled in all directions within the Viewport:  This requires some deeper integration so I could not do this while using our example of minimal_tree, however I kept my example code below as similar as I could to this example.

import 'package:cross_scroll/cross_scroll.dart';
import 'package:flutter/material.dart';
import 'package:flutter_fancy_tree_view/flutter_fancy_tree_view.dart';

class Node {
  Node({
    required this.title,
    Iterable<Node>? children,
    // The : and spread operator creates a "initialier list" which
    // users the "null aware spread operator" to add the iterated children,
    // to this node's children
  }) : children = <Node>[...?children];

  final String title;
  final List<Node> children;
}

class ScrollTreeView extends StatefulWidget {
  const ScrollTreeView({super.key});

  @override
  State<ScrollTreeView> createState() => _ScrollTreeViewState();
}

class _ScrollTreeViewState extends State<ScrollTreeView> {
  late final TreeController<Node> treeController;

  final Node root = Node(title: '/');

  @override
  void initState() {
    super.initState();
    populateExampleTree(root);
    treeController = TreeController<Node>(
      roots: root.children,
      childrenProvider: (Node node) => node.children,
    );
  }

  @override
  void dispose() {
    treeController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // Define the controllers for CrossScroll
    final horizScrollController = ScrollController();
    final vertScrollController = ScrollController();

    return SafeArea(
      child: SizedBox(
        height: 300,
        width: 500,
        child: CrossScroll(
          verticalScroll: CrossScrollDesign(),
          horizontalScrollController: horizScrollController,
          verticalScrollController: vertScrollController,
          verticalBar: const CrossScrollBar(
            thumb: ScrollThumb.alwaysShow,
          ),
          horizontalBar: const CrossScrollBar(
            thumb: ScrollThumb.alwaysShow,
          ),
          child: SizedBox(
            height: 1000,
            width: 530,
            child:
                // Block implemntation of the scroll bars on PC based systems
                // -TODO: Test that this indeed does turn off scroll bars on PC's
                // If not use platform switch to turn off CrossScroll
                ScrollConfiguration(
              behavior:
                  ScrollConfiguration.of(context).copyWith(scrollbars: false),
              child: TreeView<Node>(
                treeController: treeController,
                // NeverScroll is important to allow CrossScroll to have control.
                physics: const NeverScrollableScrollPhysics(),
                // Note: Shrinkwrap thows an error without the parent SizedBox
                // to contain it.  With the SizedBox it does not help.
                // Could try shrinkWrap on CrossScroll.
                //shrinkWrap: true,
                padding: EdgeInsets.zero,
                nodeBuilder: (BuildContext context, TreeEntry<Node> entry) {
                  return TreeIndentation(
                    entry: entry,
                    child: Row(
                      children: [
                        ExpandIcon(
                          key: GlobalObjectKey(entry.node),
                          isExpanded: entry.isExpanded,
                          onPressed: (_) =>
                              treeController.toggleExpansion(entry.node),
                        ),
                        Flexible(
                          child: Text(entry.node.title),
                        ),
                      ],
                    ),
                  );
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by baumths** [comment]
Hey @aekaero, I took a lot of inspiration from the trees in [flutter's devtools app](https://github.com/flutter/devtools) when building the new version of this package. Check out how they worked around this issue:

They created an `OffsetScrollbar` widget that is translated into the viewport:
https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/shared/ui/utils.dart#L98
Here's how it is being used in the inspector tree: https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/inspector/inspector_tree_controller.dart#L1048

> Just a nit from your previous comment: remember to create your `ScrollController`s in a `StatefulWidget` similar to how the `TreeController` is being created. Also make sure to call `dispose()` for both scroll controllers to release resources.

**Comment by aekaero** [comment]
@baumths, is there a way to determine what the rendered width of the tree is?  Either as it is currently displayed or if it were fully expanded?  Much thanks!

**Comment by baumths** [comment]
> @baumths, is there a way to determine what the rendered width of the tree is?  Either as it is currently displayed or if it were fully expanded?  Much thanks!

Unfortunately not out of the box, but you could try the following:

```dart
// In flutter you can't really get the size of a widget before it is rendered, this is a hot topic :)

// This would be located in the state of the widget whose build method returns the tree view.

@override
void initState() {
  super.initState();
 WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
    final renderBox = context.findRenderObject()! as RenderBox;
    print(renderBox.size);
  }
}

// Then after the first frame you would have the size of the tree
```
