### ISSUE TITLE
How to change solid line to dashed line

### ISSUE THREAD

**Issue by thpthang-nextfunc** [baumths/flutter_tree_view#49]

**Comment by baumths** [comment]
Hi @thpthang-nextfunc.

Unfortunately dashed lines are currently not supported.

**Comment by thpthang-nextfunc** [comment]
I found a way to add this properties. How can I contribute to your project?

**Comment by baumths** [comment]
You could open a PR and I'd review it once I have some spare time or we could discuss what you found and I'd implement it later taking the project structure into account.

I'm also open to suggestions. Feel free to go with what's better for you.

**Comment by thpthang10** [comment]
I think it's better if you add new properties to your current project with your style. You can refer my fork here. Hope it help. :)

https://github.com/thpthang10/flutter_tree_view

**Comment by thpthang10** [comment]
This is my personal git. The above is my company's git, it will be changed in the future so I switch to my personal account.

**Comment by thpthang10** [comment]
And thank you for creating a useful library for the community.

**Comment by baumths** [comment]
> I think it's better if you add new properties to your current project with your style. You can refer my fork here. Hope it help. :)
>
> https://github.com/thpthang10/flutter_tree_view

I took a look at your implementation and I'm concerned that all those gradient shaders could lead to some performance issues, so I did a small research and found the [path_drawing](https://pub.dev/packages/path_drawing) package on pub as well as this nice [article](https://meysam-mahfouzi.medium.com/drawing-curved-dashed-lines-in-flutter-b5d0645b04c8) about adding dashed lines using the path_drawing package. Seems like it uses [Path.computeMetrics](https://api.flutter.dev/flutter/dart-ui/Path/computeMetrics.html) to add dashed lines in a more performant way as suggested by the flutter team in https://github.com/flutter/flutter/issues/4858.

> Just a small disclaimer, I did not try anything out in code but from what I read about the implementation, it is the "correct" way of doing it.

I'm currently working on drag and drop support for this package and it is on the top of my priority list so the dashed lines feature will have to wait for now as I have very little spare time to work on this project and I'm dedicating all of it into the drag and drop feature.

For now, users that may want dashed lines could copy the current [`ConnectingLines` implementation](https://github.com/baumths/flutter_tree_view/blob/main/lib/src/tree_indentation.dart#L359-L508) and apply the dashing algorithm to the path created in the `paint()` method of `_ConnectingLinesPainter`.

---

> And thank you for creating a useful library for the community.

Thank you for trying it out and providing feedback! :blue_heart:

**Comment by baumths** [comment]
> I think it's better if you add new properties to your current project with your style. You can refer my fork here. Hope it help. :)
>
> https://github.com/thpthang10/flutter_tree_view

I took a look at your implementation and I'm concerned that all those gradient shaders could lead to some performance issues, so I did a small research and found the [path_drawing](https://pub.dev/packages/path_drawing) package on pub as well as this nice [article](https://meysam-mahfouzi.medium.com/drawing-curved-dashed-lines-in-flutter-b5d0645b04c8) about adding dashed lines using the path_drawing package. Seems like it uses [Path.computeMetrics](https://api.flutter.dev/flutter/dart-ui/Path/computeMetrics.html) to add dashed lines in a more performant way.

> Just a small disclaimer, I did not try anything out in code but from what I read about the implementation, it is the "correct" way of doing it, as suggested by the flutter team in https://github.com/flutter/flutter/issues/4858.

I'm currently working on drag and drop support for this package and it is on the top of my priority list so the dashed lines feature will have to wait for now as I have very little spare time to work on this project and I'm dedicating all of it into the drag and drop feature.

For now, users that may want dashed lines could copy the current [`ConnectingLines` implementation](https://github.com/baumths/flutter_tree_view/blob/main/lib/src/tree_indentation.dart#L359-L508) and apply the dashing algorithm to the path created in the `paint()` method of `_ConnectingLinesPainter`.

---

> And thank you for creating a useful library for the community.

Thank you for trying it out and providing feedback! :blue_heart:

**Comment by thpthang-nextfunc** [comment]
Hi @baumths Can you help me solve this issue? Just want to hear your idea.

  ```
 return Column(
          children: [
            MyTreeTile(
              // Add a key to your tiles to avoid syncing descendant animations.
              key: ValueKey(entry.node),
              // Your tree nodes are wrapped in TreeEntry instances when traversing
              // the tree, these objects hold important details about its node
              // relative to the tree, like: expansion state, level, parent, etc.
              //
              // TreeEntrys are short lived, each time TreeController.rebuild is
              // called, a new TreeEntry is created for each node so its properties
              // are always up to date.
              entry: entry,
              // Add a callback to toggle the expansion state of this node.
              onTap: () => treeController.toggleExpansion(entry.node),
            ),
            //
            // How can I draw a vertical line for a widget (it show a blank on the folder tree)
            Text('data'),
          ],
        );
```

**Comment by thpthang-nextfunc** [comment]
![Screenshot 2023-04-17 at 15 37 34](https://user-images.githubusercontent.com/69334860/232431356-1cbfb1bf-ca22-43fe-8984-6e20db358f93.png)

**Comment by baumths** [comment]
Hey @thpthang-nextfunc.

In this case, its because the lines are painted for the widget subtree of `TreeIndentation` which is created by the above `MyTreeTile` and your text widget is in a column outside of `MyTreeTile`.

I suggest that you copy the implementation of `MyTreeTile` and wrap its row in a column and place your vertical widgets there.

Try it out and let me know if it works.

**Comment by thpthang-nextfunc** [comment]
![Screenshot 2023-04-17 at 18 53 38](https://user-images.githubusercontent.com/69334860/232476912-c5664f98-db6a-4816-9567-4a6bfba1a884.png)
I worked, except for the first folder.

**Comment by baumths** [comment]
> It worked, except for the first folder.

Great to hear!

About the first folder: it's the expected behavior as root nodes are currently not wrapped in any custom paint as they occupy the level 0 of the tree, therefore having no indentation applied nor guide painting.

I have been requested in the past to paint a tiny vertical line for a parent who is both expanded and has child nodes, but unfortunately I haven't had time to implement it yet.

I will probably work on both dashed lines and this little feature in the same PR at some point in the future. But again, for now I'm focusing my spare time on the drag and drop feature. Unfortunately this will have to wait.
