### ISSUE TITLE
When adding a child node to a node, setState() does not take effect, and only when expanding the node again can the newly added node be displayed.

### ISSUE THREAD

**Issue by leavky** [baumths/flutter_tree_view#50]
When adding a child node to a node, setState() does not take effect, and only when expanding the node again can the newly added node be displayed. I don't know if this is a bug or if there's something wrong with my code. Could you provide an example, please?

**Comment by baumths** [comment]
Hey @leavky!

Are you calling `TreeController.rebuild()` after adding the new child node? If not, try it out and let me know if it worked as expected.

Otherwise, could you provide an example of what you're doing so I can investigate?

**Comment by leavky** [comment]
Thank you for your answer. I didn't use treeController.rebuild() before, but now it works.
