### ISSUE TITLE
Is it possible to have no interaction ?

### ISSUE THREAD

**Issue by vptcnt** [baumths/flutter_tree_view#52]
Hello

Is it possible to display a full expanded tree view, but to not have any interaction with it ?
Just display hierarchical data, just scrollable, but with no click on the nodes.

**Comment by baumths** [comment]
Hey @vptcnt!

That's totally doable. Those interactions are added at the node widget level, you have to provide `null` to any "`on`" callback your widgets might have, like `onPressed` and `onTap`.

If that is not enough and you want to make sure your tree nodes are not tappable, you could wrap them with the [`IgnorePointer`](https://api.flutter.dev/flutter/widgets/IgnorePointer-class.html) widget.
> Keep in mind that the `IgnorePointer` widget will also remove hover effects and alikes.
