### ISSUE TITLE
Selected node not highlighted 

### ISSUE THREAD

**Issue by BS-Wissem** [baumths/flutter_tree_view#54]
Hello,
Thanks for this great package, I updated  from version 0.5 and I noticed that the selected node is no more highlighted, and the associated property is missing.
Thank you.

**Comment by baumths** [comment]
Hey!

Could you please elaborate the issue? I'm not sure about which highlight/selected behavior changed, is it the example app?

**Comment by BS-Wissem** [comment]
Hello,
Thanks for your reply, there used to be `appController.toggleSelection(nodeScope.node.id, true);` which changes the text color of the selected node to blue (default color value).
It was called in onTap after calling toggleSelection, actually there is only `treeController.toggleExpansion(entry.node);`
![image](https://github.com/baumths/flutter_tree_view/assets/109534565/1d52ed68-54bb-415b-b966-1c24358186ba)

Regards.

**Comment by baumths** [comment]
So, this is from the example app of the pre 1.0 versions, I decided to remove the selection behavior from the example app as it is not supported by the package and could cause confusion for some users.
