### ISSUE TITLE
How to dynamically load tree for selected root?

### ISSUE THREAD

**Issue by bambinoua** [baumths/flutter_tree_view#55]
I have an initial tree which contains few roots
```
root 1
root 2
root 3         > // this one has children
```

I want to load the tree which belongs to `root 3` when user clicks on `FolderButton`. Certainly I want to do loading when node is in **_collapsed_** state but all tree nodes are expanded by default. _(I think that is a bug moreover if node is a leaf so how can it be expanded or collapsed?)_

To change expansion state I need to call `controller.toggleExpansion(node)` each time user clicks on `FolderButton`. But when I call it on expanded node it will be collapsed so I need to do click again? And finally I need to load tree **_after_** expanding! So how to implement tree loading on demand? How can I subscribe on expansion state change?

**Comment by baumths** [comment]
Hey @bambinoua!

This kind of business logic is up to you to decide, since its you the one updating the expansion state from a button press, check for the expansion state of the node prior to updating it, also, keep track of already loaded nodes which will then enable you to reload the children of a node. 

For leaf nodes, you can pass a different callback or `null` to your button, or even another widget to `nodeBuilder`.

**Comment by bambinoua** [comment]
The problem one is the leaf cannot be expanded or collapsed, basically. So I think it should be `null` initially. Only nodes with children can be expanded or collapsed.

The problem two is why node which is actually not loaded (lazy loading) is already expanded? So the next `toogleExpansion` will collapse its status which is wrong from UX point of view. I.e. I need to click `FolderButton` again to expand it.

I think the logic of defining expansion state should be reconsidered. Expansion should be available only if node has children, if node has no children so it cannot be expanded because it is a leaf actually.

**Comment by baumths** [comment]
> The problem one is the leaf cannot be expanded or collapsed, basically. So I think it should be `null` initially. Only nodes with children can be expanded or collapsed.
> 
> The problem two is why node which is actually not loaded (lazy loading) is already expanded? So the next `toogleExpansion` will collapse its status which is wrong from UX point of view. I.e. I need to click `FolderButton` again to expand it.
> 
> I think the logic of defining expansion state should be reconsidered. Expansion should be available only if node has children, if node has no children so it cannot be expanded because it is a leaf actually.

Again, that's up to you to decide for your use case.

This behavior can change depending on what kind of tree view you are displaying to your users, be it a catalog, a collection view, taxonomy, etc. This package provides an abstract tree view for your apps, which you can then apply your business logic to it.

Also. You don't have to rely on what's provided, you can extend `TreeController` and update it to accomodate your needs.
