### ISSUE TITLE
[Help] DataTable inside tree, when node !hasChildren

### ISSUE THREAD

**Issue by vivagelive** [baumths/flutter_tree_view#58]
Hi! Is it possible to insert a datatable into a node if there are no children? Have you any advise or solution? Thanks for your reply.

**Comment by baumths** [comment]
Hey, sorry for the delay, I've been busy lately. 

I'm not sure I understand the question. Could you elaborate or add an example of the desired behavior?

Having conditional widgets should be straightforward:

```dart
TreeView(
  ...,
  nodeBuilder(BuildContext context, TreeEntry entry) {
    if (entry.node.isLeaf) {
      return DataTable(...);
    }
    return MyNodeWidget(...);
  }
)
```

**Comment by vivagelive** [comment]
Hi, sorry for late answer.  I tried many options and was able to do what I wanted. Thanks for your answer. Awesome package, Thx
