### ISSUE TITLE
how to fetch and load node data on tap

### ISSUE THREAD

**Issue by Kushwaha2021** [baumths/flutter_tree_view#59]

**Comment by baumths** [comment]
Hi @Kushwaha2021 

Please take a look at the [lazy loading example](https://github.com/baumths/flutter_tree_view/blob/main/example/lib/src/examples/lazy_loading.dart).

**Comment by Kushwaha2021** [comment]
add children to given node on tap

**Comment by Kushwaha2021** [comment]
I have tree structure but it contains large data with children unto 5-6 level so It was taking time to build tree , therefore I decided to add children on given node on tap only

**Comment by Kushwaha2021** [comment]
thanks for your response !
