### ISSUE TITLE
Each row of the current node must not occupy the maximum space

### ISSUE THREAD

**Issue by ismanong** [baumths/flutter_tree_view#66]
Hello!Thank you.Thank you for yourThanks for the package!

But I found a problem when I used it and couldn't solve it.

I used the following code to realize that a checkbox checkbox is displayed on the rightmost side of the phone, but the position is never close to the rightmost side, always leaving a blank distance.
After checking your code, I still don't know what is causing this.

Can you help me?

```dart
TreeIndentation(
            entry: entry,
            // Provide an indent guide if desired. Indent guides can be used to
            // add decorations to the indentation of tree nodes.
            // This could also be provided through a DefaultTreeIndentGuide
            // inherited widget placed above the tree view.
            guide: const IndentGuide.connectingLines(indent: 48),
            // The widget to render next to the indentation. TreeIndentation
            // respects the text direction of `Directionality.maybeOf(context)`
            // and defaults to left-to-right.
            child: Padding(
              padding: const EdgeInsets.fromLTRB(4, 8, 8, 8),
              child: Row(
                children: [
                  // Add a widget to indicate the expansion state of this node.
                  // See also: ExpandIcon.
                  // FolderButton(
                  //   isOpen: entry.hasChildren ? entry.isExpanded : null,
                  //   onPressed: entry.hasChildren ? onTap : null,
                  // ),
                  if (entry.hasChildren)
                    ExpandIcon(
                      key: GlobalObjectKey(entry.node),
                      isExpanded: entry.isExpanded,
                      onPressed: (_) =>
                          treeController.toggleExpansion(entry.node),
                    ),
                  Flexible(
                    child: Text(entry.node.title),
                  ),
                  Expanded(child: SizedBox()),
                  if (entry.node.children.isEmpty)
                    Checkbox(
                      checkColor: Colors.white,
                      // fillColor: MaterialStateProperty.resolveWith(getColor),
                      value: false,
                      onChanged: (bool? value) {
                        widget.onSelected(entry.node);
                      },
                    ),
                ],
              ),
            ),
          )
```
![d1748051824f8584d8f7bb620a0c859](https://github.com/baumths/flutter_tree_view/assets/13862699/978f4568-cb67-4258-bcf9-08c4d35fd08b)

**Comment by baumths** [comment]
Hey @ismanong , thank you for using this package!

It should be happening because of the `Flexible` widget wrapping `Text`. You could either replace the 
`Flexible` widget by the `Expanded` widget or replace your `Expanded(child: SizedBox())` by an `Spacer` widget.

Try it out and let me know if it works. 😊

**Comment by ismanong** [comment]
Valid, thank you, I didn't like to use Flexible before and didn't remove it based on the rigor of the author's example, which was under the impression that it was a scalable box.
May I ask why this is such a strange feature?

**Comment by baumths** [comment]
The `Flexible` widget prevents the layout from overflowing when the text is bigger than the available width. The main difference is that the `Expanded` widget will take all the space it can while the `Flexible ` will take as little space as it needs to fit its child.

**Comment by ismanong** [comment]
Thank you, I understand and appreciate your patience.
