### ISSUE TITLE
ExpandIcon should have a IconData field to overwrite Icons.expand_more

### ISSUE THREAD

**Issue by stephane-archer** [baumths/flutter_tree_view#67]

**Comment by baumths** [comment]
Hey @stephane-archer , thank you for using the package!

The `ExpandIcon` widget is part of the flutter flamework.

**Comment by stephane-archer** [comment]
@baumths you are welcome, I didn't know ExpandIcon was part of Flutter. If we can't customize ExpandIcon then I would be glad if we can replace it with another class of your own or that the user define.

**Comment by baumths** [comment]
As the flutter framework already provides such a widget, I would recommend you to file an issue there so they add more customization options to the `ExpandIcon` widget instead.

In the meantime, I've put together an example using the [AnimatedRotation](https://api.flutter.dev/flutter/widgets/AnimatedRotation-class.html) widget, which you can copy and tweak to look as desired:

```dart
class MyExpandIcon extends StatefulWidget {
  const MyExpandIcon({super.key});

  @override
  State<MyExpandIcon> createState() => MyExpandIconState();
}

class MyExpandIconState extends State<MyExpandIcon> {
  bool isExpanded = false;

  @override
  Widget build(BuildContext context) {
    return IconButton(
      onPressed: () => setState(() => isExpanded = !isExpanded),
      icon: AnimatedRotation(
        turns: isExpanded ? 0.5 : 0,
        duration: kThemeAnimationDuration,
        child: const Icon(Icons.chevron_right),
      ),
    );
  }
}
```
