### ISSUE TITLE
How to appear the horizontal scrollbar ?

### ISSUE THREAD

**Issue by wxmayifei** [baumths/flutter_tree_view#69]
I'm new in flutter, maybe this is a easy issue.

I use this wrapped in a container,  such as the following code

```
Container(
   height: 300,
   width: 500,
   child: TreeView<MyNode>()
)
```

when the height of treeview is larger than 300, will appear the vertical scrollbar
but why  when the width is larger than 500, the horizontal scrollbar will never appear ? 

Please help me

thanks

**Comment by baumths** [comment]
Hi @wxmayifei ,

Horizontal scrolling is not supported yet.

**Comment by anjaliAzure** [comment]
Hello @baumths 

Now, are you giving horizontal scroll support? or have any other option where we can achieve both scroll.
