### ISSUE TITLE
Color of selected node

### ISSUE THREAD

**Issue by vivagelive** [baumths/flutter_tree_view#77]
Hello. Can I do it on my own or programmatically change the color of the selected node? Or somehow show that the node is highlighted/selected
Thank you.

**Comment by bybabek** [comment]
decoration = BoxDecoration(
            border: details.mapDropPosition(
              whenAbove: () => Border(top: borderSide),
              whenInside: () => Border.fromBorderSide(borderSide),
              whenBelow: () => Border(bottom: borderSide),
            ),
            color: details.mapDropPosition(
              whenAbove: () => Colors.transparent,
              whenInside: () => hoverColor,
              whenBelow: () => Colors.transparent,            ),
          );
