### ISSUE TITLE
Feature Request:  Add onWillAcceptWithDetail

### ISSUE THREAD

**Issue by CoreySafetyIndicators** [baumths/flutter_tree_view#80]
Hey,
 It would be nice to add onWillAcceptWithDetail to the TreeDragTarget.  The use case is if you want to use the extension that was made in the Drag/Drop example than has multiple zone, each zone needs to be validated.  

Example: 

```
TreeDragTarget<Node>(
  node: entry.node,
  onNodeAccepted: onNodeAccepted,
  builder: (BuildContext context, TreeDragAndDropDetails<Node>? details) {
    var isValid = true;
    if (details != null) {
      details.mapDropPosition(
          whenAbove: () { isValid = false;},
          whenInside: () { isValid = childValidCheck(details); },
          whenBelow: () {isValid = siblingValidCheck(details); },
      );
    }
  }
)

```

I am hoping this example makes sense to what I am trying to convey.

**Comment by baumths** [comment]
Hey @CoreySafetyIndicators 

I'm currently completely out of free time to work on this project, so I won't be able to look into this for quite a while.

If you're willing to submit a PR I'll do my best to find time to review it.

**Comment by baumths** [comment]
I finally found time to take a loot into this. Unfortunately the `onWillAccept*` is only called once when the dragging data enters the drag target. There's no implicit way to validate each zone, you might need to do it inside TreeDragTarget's builder and again in `onNodeAccepted` (or cache the value).
