### ISSUE TITLE
Duplicated key in scaffold

### ISSUE THREAD

**Issue by arcas0803** [baumths/flutter_tree_view#83]
When you render a new tree on a router stack that already has a tree with nodes sharing between both, a duplicated keys error is thrown.

This is because you are using the node object to create the key of the entry. It would be nice to let the devs set the key for each node. If the key is not provided, use the salt function, if it is, use the key provided for every entry.

**Comment by baumths** [comment]
Sorry it took me so long to look into this.

I've just pushed [a6a3685](https://github.com/baumths/flutter_tree_view/commit/a6a368507393442c62f05353ae813877a4ab8fd8), which should fix this issue.

This fix will be landing in the next release, no breaking changes.

After upgrading there will be nothing to do on your side, it should just work as expected.
