### ISSUE TITLE
Drag only on selected target

### ISSUE THREAD

**Issue by urvashik-7span** [baumths/flutter_tree_view#86]
I want to implement drag functionality only on particular widgte/Icon click not whole tree child click.
How can I implement this?

**Comment by baumths** [comment]
Hey @urvashik-7span, thank you for using this package!

It should be as easy as moving your TreeDraggable widget from around your tree tile down the widget tree to wrap your specific widget/icon.

It's in my todo list to update the drag and drop example an demonstrate this use case.

**Comment by baumths** [comment]
I've posted an example implementation for drag handlers on https://github.com/baumths/flutter_tree_view/issues/74#issuecomment-2045919251, but forgot to mention it here.

For the demo app, I've decided to keep it simple and handle the mobile scroll/drag issue through long press.

I'm going to close this issue for now. Feel free to reopen if you have any further questions. :blush:
