### ISSUE TITLE
Show root node in tree

### ISSUE THREAD

**Issue by Uche01** [baumths/flutter_tree_view#88]
I have a use case where showing the root node in the tree structure is necessary, is there a way to do this?

**Comment by baumths** [comment]
Hey @Uche01.

It's totally doable. Provide your root node to `TreeController.roots`:
```dart
// Instead of
final controller = TreeController(
  roots: rootNode.children,
  ...
);

// Do
final controller = TreeController(
  roots: [
    rootNode,
  ],
  ...
);
```

Hope it helps!

**Comment by Uche01** [comment]
This works! Thank you @baumths
