### ISSUE TITLE
Multiple Widgets used the same GlobalKey

### ISSUE THREAD

**Issue by Uche01** [baumths/flutter_tree_view#90]
I am using draggable tree node. However I suddenly started getting the error when I expand a node. `Exception caught by widgets library. Multiple widgets used the same GlobalKey`. All my tree widgets are Stateless and I am not using any GlobalKey in the widgets yet I get the above error. 

Any hints on using keys with this library?

**Comment by baumths** [comment]
Hey, I'm aware of this issue, thank you for pointing it out. Will be looking into it later today.

Just out of curiosity, are you using the standard tree view or the animated one?

**Comment by Uche01** [comment]
I am using `AnimatedTreeView`

**Comment by baumths** [comment]
I can't seem to be able to reproduce it currently, is it happening consistently for you? If so, could you provide a small reproducible example for me to work on?

**Comment by Uche01** [comment]
Apparently the issue seems to be from my code. I was adding two exact same node instance to a parent's children array EG
```
Node parent = Node()
Node child1 = Node();
parent.children = [child1];
parent.addChild(child1);
child1.setParent(parent)
```

This may help you reproduce the issue @baumths

**Comment by baumths** [comment]
Oh, thank you, glad you worked it out!

I'm going to close this issue for now, feel free to reopen it if necessary. :blush:
