### ISSUE TITLE
I am finding it difficult to restore expanded nodes on widget rebuild

### ISSUE THREAD

**Issue by Uche01** [baumths/flutter_tree_view#92]
I have a usecase where I save node expansion state using provider, when there is need to rebuild, I'm unable to restore the expanded nodes.

Where exactly do I need to place the `treeController.setExpansionState(node, bool)` method? I tried putting in the `nodeBuilder` method however, there appears to be some inconsistencies between `AnimatedTreeView` and `TreeView`.

Are there inbuilt method to restore node state on widget rebuild?

PS: I overrode the `setExpansionState` and `getExpansionState` methods in TreeController to support the state in Provider

**Comment by baumths** [comment]
State restoration _should_ be done in the `initState`, `didChangeDependencies` and `didUpdateWidget` methods on the State of a StatefulWidget; never in widget builders (for performance reasons).

**Comment by Uche01** [comment]
But I can't access the `node` object in these methods. I need the node to be able to call `treeController.setExpansionState(node, true)`. Can you help with examples?

**Comment by baumths** [comment]
Your nodes are somehow being loaded into memory, right? You could restore the expansion state when your nodes are being instantiated, for example.

Also, check out version 1.6 which exposed the `TreeController.toggledNodes` Set. It could be used instead of (get|set)ExpansionState() to restore your toggled nodes.

**Comment by Uche01** [comment]
Hi @baumths still having issues restoring expansion state on app load here are some snippets:
```
initState() {
....
    Set<Node> expandedNodes = context.read<TreeNodeState>().expandedNodes;

    treeController = MyTreeController<Node>(
      expandedNodes: expandedNodes,
      roots: [examRoot, qbRoot],
      childrenProvider: (Node node) =>
          node.children as Iterable<Node<Node<dynamic>>>,
      parentProvider: (Node node) => node.parent,
    );
}
```

TreeController:
```
class MyTreeController<T extends Object> extends TreeController<T> {
  MyTreeController({
    required this.expandedNodes,
    required super.roots,
    required super.childrenProvider,
    super.parentProvider,
  });

  Set<T> expandedNodes;

  @override
  bool getExpansionState(T node) => expandedNodes.contains(node);

  @override
  void setExpansionState(T node, bool expanded) {
    expanded ? expandedNodes.add(node) : expandedNodes.remove(node);
  }
...
```

Can you provide a snippet example on how I could possible restore node state?

PS: `expandedNodes` is a set I store the `nodes` that are expanded using `Provider`.
