### ISSUE TITLE
MultiColumn TreeView

### ISSUE THREAD

**Issue by vmtest888** [baumths/flutter_tree_view#93]
The project is great. I have a little suggestion. Can you add a MultiColumn TreeView? There are columns on the tiewview. You can drag the column headers to display different data in each column.

**Comment by baumths** [comment]
Hey @vmtest888. I'm glad you liked the project!

What you're looking for is a `TreeTable` widget which I don't plan on supporting in this package. However, the Flutter team has plans for a new `TreeTableView` widget for the [two_dimensional_scrollables](https://pub.dev/packages/two_dimensional_scrollables) package once they finish the 1D and 2D tree views that they are currently working on.
